### ISSUE TITLE
Unable to control powerpoint preso (how to map keys?)

### ISSUE THREAD

**Issue by regulatre** [alxn1/wjoy#85]
It seems wjoy requires some sort of key mapping to use the wii arrows to move things on the screen (or advance slides on a presentation). 

In Linux I used wiimote to control my preso using the wiimote. it worked great. 

However wjoy seems to requires some sort of translation layer application? wiiControl is the closest I could come, but it's no longer maintained and requires Java 6. 

Any hints or suggestions? 
Thanks

**Comment by alxn1** [comment]
Sorry, i don't know analogs for OS X. :)

**Comment by regulatre** [comment]
Found "enjoy2" application. Its primitive but it does the job nicely. It talks to wjoy and translate the joystick movements / buttons into key events. I can use it to control my powerpoint presentation. Thanks!
