### ISSUE TITLE
Wii U Pro Controller not connecting with OS X 10.11 (El Capitan)

### ISSUE THREAD

**Issue by zacharyvincze** [alxn1/wjoy#86]
**_What's wrong?**_
This application used to work fine with Yosemite, but after i updated, I soon found out that my controllers would no longer connect.  I've gotten the application to start up fine and all that, but when I sync my controller it vibrated to signify that the controller was connected.  The application said that the discovery was finished and about one second later, the led turned off on my pro controller and then the application said that the Wiimote was disconnected.

Or at least the controller used to vibrate, now it won't even do that, it'll only say that the discovery has finished.  No leds light up on my controller or anything like that.

**_What have you tried so far?**_
- Remove the controller from bluetooth in preferences
- Restart the computer
- Reinstall the application
- Enabled one button connection (Which asks for a pairing code for some reason)

_None of these things have worked._

**_Why should this be fixed?**_ I want to figure out this problem because I used Wjoy all the time to play games on my iMac instead of having to use a keyboard.  If anyone can help me out with this issue, It'd be greatly appreciated.

**_Extra Notes**_
- I'm running on OS X 10.11 (El Capitan)
- I'm using WJoy version 0.71
- I'm trying to connect using a Wii U Pro controller
- Bluetooth is built into my computer

**Comment by zacharyvincze** [comment]
Problem solved.  I had to disable system integrity mode on the iMac.

**_To do this**_
- Restart your mac in recovery mode (Hold Command + R on startup)
- Open Utilities > Terminal
- Run "csrutil disable" in the command line
- If you want to enable system integrity mode, repeat the upper steps but instead type "csrutil enable" in the command line.

Hope this helps you out!

**Comment by nunziotocci** [comment]
I just bought a Wii U Pro controller (I think it is third-party though, it has no Wii U logo), and I have no previous experience with wjoy. Bluetooth is not recognizing any wii device, not a wiimote, not a pro controller.

I have disabled System Integrity Protection.
I have also tried the solution in #68.

UPDATE: I rebooted and my mac detects wiimotes now, but still no pro controller.

**Comment by zacharyvincze** [comment]
Nunzuitocci, if it's a third party controller, I doubt that it'll actually be supported.  You'll probably have to get a normal pro controller if you want to be able to connect it to the computer.

**Comment by nunziotocci** [comment]
Zvincze, I read somewhere else that is should still work with a third-party controller.

But I did some more research, and I think it is down to the bluetooth version.
The controller uses Bluetooth 4, my Mac Mini has Bluetooth 2.1 + EDR.

I also heard that they should be backwards compatible, but I can't even pair to the pro controller in System Preferences.

**Comment by zacharyvincze** [comment]
Nunziotocci, it must be your bluetooth then.  Even if it didn't connect with WJoy, you should've still saw it in the bluetooth menu.  You could probably get an adapter for that.

**Comment by nunziotocci** [comment]
Zvincze, Yeah, I should probably get a dongle or something if I want to get it working. Thank you for your input.

**Comment by snesgab** [comment]
how come wjoy doesnt work on 11.2 serria any help
