### ISSUE TITLE
Update download location

### ISSUE THREAD

**Issue by tsparber** [alxn1/wjoy#88]
As Google Code will be dead on [25 Jan](http://google-opensource.blogspot.com.au/2015/03/farewell-to-google-code.html), would you mind to move the [0.7.1 release files](https://code.google.com/p/wjoy/downloads/detail?name=wjoy%200.7.1.dmg&can=2&q=) to somewhere else? (eq. [GitHub releases](https://github.com/blog/1547-release-your-software))

(Refs https://github.com/caskroom/homebrew-cask/issues/17075)

**Comment by alxn1** [comment]
Latest (WJoy 0.7.1) dmg accessible with yandex-disk: https://yadi.sk/d/Fj6PYXpKiMPwc
And readme.md has link to it. :)

**Comment by tsparber** [comment]
@vitorgalvao Do you think this can be used?

**Comment by vitorgalvao** [comment]
@tsparber If it is linked officially and it works, sure.

**Comment by tsparber** [comment]
@alxn1 The yandex-disk image does not allow direct downloads (hotlinking). This is needed to work in a homebrew cask (https://github.com/caskroom/homebrew-cask/pull/17312). The [google code archive](https://code.google.com/archive/p/wjoy/) link also yields to a [404](https://storage.googleapis.com/google-code-archive-downloads/v1/code.google.com/wjoy/wjoy%200.7.1.dmg).

**Comment by alxn1** [comment]
Ok, i create release on github: https://github.com/alxn1/wjoy/releases/download/0.7.1/wjoy.0.7.1.dmg

**Comment by tsparber** [comment]
Thank you!
